#指定Eureka服务地址
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka,http://root:root@localhost:8762/eureka
    registry-fetch-interval-seconds: 30  # 每隔多久去更新下本地缓存信息
  instance:
    lease-renewal-interval-in-seconds: 90     #心跳间隔
    lease-expiration-duration-in-seconds: 30  #多久没发送，就认为你宕机了

#指定具体服务的负载均衡
# 编写服务名称
SEARCH:
  ribbon:
    #    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# feign和hystrix组件整合的内容
feign:
  hystrix:
    enabled: true

version: v1

#指定服务名称
spring:
  application:
    name: CUSTOMER-${version}
  #连接rabbittmq
  rabbitmq:
    host: 192.168.237.129
    port: 5672
    username: test
    password: test
    virtual-host: /test

 

server:
  port: 8080
