
#指定具体服务的负载均衡
# 编写服务名称
SEARCH:
  ribbon:
    #    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# feign和hystrix组件整合的内容
feign:
  hystrix:
    enabled: true


#指定服务名称
spring:
  #连接rabbittmq
  rabbitmq:
    host: 192.168.237.129
    port: 5672
    username: test
    password: test
    virtual-host: /test

 
